export const FETCH_APARTMENTS_STARTED = 'FETCH_APARTMENTS_STARTED';
export const FETCH_APARTMENTS_SUCCESS = 'FETCH_APARTMENTS_SUCCESS';
export const FETCH_APARTMENTS_FAIL = 'FETCH_APARTMENTS_FAIL';

export const EDIT_APARTMENT_STARTED = 'EDIT_APARTMENT_STARTED';
export const EDIT_APARTMENT_SUCCESS = 'EDIT_APARTMENT_SUCCESS';
export const EDIT_APARTMENT_FAIL = 'EDIT_APARTMENT_FAIL';
export const EDIT_APARTMENT = 'EDIT_APARTMENT';
export const ADD_APARTMENT = 'ADD_APARTMENT';
export const AVAILABLE_APARTMENTS = 'AVAILABLE_APARTMENTS';
export const UPDATE_APARTMENT = 'UPDATE_APARTMENT';
export const DELETE_APARTMENT = 'DELETE_APARTMENT';

export const APARTMENT_UPDATE = 'APARTMENT_UPDATE';
export const APARTMENT_CREATE = 'APARTMENT_CREATE';
export const APARTMENT_FETCH_ALL_SUCCESS = 'APARTMENT_FETCH_SUCCESS';
export const APARTMENT_FETCH_SUCCESS = 'APARTMENT_FETCH_SUCCESS';
export const APARTMENT_SAVE_SUCCESS = 'APARTMENT_SAVE_SUCCESS';
export const APARTMENT_DELETE_SUCCESS = 'APARTMENT_DELETE_SUCCESS';

export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER = 'LOGIN_USER';